theme: jekyll-theme-minimal
title: Edward C. Huang
# description: Computer Scientist & Paleobiologist
logo: https://media.licdn.com/dms/image/C4D03AQHCWeK0m5Mx7g/profile-displayphoto-shrink_800_800/0/1589244752080?e=1703721600&v=beta&t=LasxcVxHsR9vl6UotUju8t0dVniL9p4aofRcZBJw8H0
show_downloads: false
